language: java
jdk: openjdk11

env:
  - NODE_VERSION="12.18"

before_install:
  # Disable all Travis default repositories
  - sed -i "s/activeByDefault>true</activeByDefault>false</g"  ~/.m2/settings.xml
  - nvm install $NODE_VERSION

script:
  - mvn -B -e -V clean install -Pproduction

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
