language: java
jdk: oraclejdk11

before_install:
  # Disable all Travis default repositories
  - sed -i "s/activeByDefault>true</activeByDefault>false</g"  ~/.m2/settings.xml

script:
  - mvn -B -e -V clean install -Pproduction

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
