# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '18 08 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exempt-issue-labels: 'help wanted'
        stale-issue-message: 'There has not been any activity on this issue for 60 days and it is going to be marked as stale and closed in 7 days.'
        stale-pr-message: 'There has not been activity on this pull request for 180 days and it will be marked as stale and closed in 7 days.'
        days-before-issue-stale: 180
        days-before-pr-stale: 60
        days-before-close: 7
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
